// Mock Data for Development and Testing

import type {
  InfoArticle,
  FAQ,
  Campaign,
  TrainingModule,
  Lesson,
  Quiz,
  AnalyticsMetric,
  EngagementData,
  GeoData,
  DeviceData,
} from '../types';

// Info Hub Mock Data
export const mockInfoArticles: InfoArticle[] = [
  {
    id: '1',
    country: 'nigeria',
    category: 'legal',
    title: 'Legal Requirements for International Migration',
    slug: 'legal-requirements-international-migration',
    content: 'Understanding the legal requirements for international migration is crucial for a safe and successful journey...',
    lastUpdated: '2025-10-15',
    author: 'SAFE-MIT Team',
    readTime: 8,
    tags: ['legal', 'documentation', 'visa'],
  },
  {
    id: '2',
    country: 'nigeria',
    category: 'safety',
    title: 'Identifying and Avoiding Migration Scams',
    slug: 'identifying-avoiding-migration-scams',
    content: 'Migration scams are unfortunately common. Learn how to protect yourself...',
    lastUpdated: '2025-10-10',
    author: 'Safety Division',
    readTime: 6,
    tags: ['safety', 'scams', 'fraud'],
  },
  {
    id: '3',
    country: 'senegal',
    category: 'employment',
    title: 'Opportunités d\'emploi à l\'étranger',
    slug: 'opportunites-emploi-etranger',
    content: 'Découvrez comment trouver des opportunités d\'emploi légitimes à l\'étranger...',
    lastUpdated: '2025-10-12',
    author: 'Équipe SAFE-MIT',
    readTime: 10,
    tags: ['emploi', 'opportunités', 'travail'],
  },
  {
    id: '4',
    country: 'morocco',
    category: 'rights',
    title: 'حقوقك كمهاجر',
    slug: 'your-rights-as-migrant',
    content: 'تعرف على حقوقك الأساسية كمهاجر وكيفية حمايتها...',
    lastUpdated: '2025-10-08',
    author: 'فريق SAFE-MIT',
    readTime: 7,
    tags: ['حقوق', 'حماية', 'قانون'],
  },
  {
    id: '5',
    country: 'kenya',
    category: 'health',
    title: 'Huduma za Afya kwa Wahamiaji',
    slug: 'health-services-migrants',
    content: 'Jifunze jinsi ya kupata huduma za afya muhimu unaposafarisha...',
    lastUpdated: '2025-10-14',
    author: 'Timu ya SAFE-MIT',
    readTime: 5,
    tags: ['afya', 'huduma', 'bima'],
  },
];

export const mockFAQs: FAQ[] = [
  {
    id: '1',
    country: 'nigeria',
    question: 'What documents do I need for legal migration?',
    answer: 'For legal migration, you typically need a valid passport, visa for your destination country, travel insurance, proof of funds, and any required health certificates. Always verify specific requirements with the embassy of your destination country.',
    category: 'legal',
    votes: 245,
    isMyth: false,
  },
  {
    id: '2',
    country: 'nigeria',
    question: 'Is it true that I can get a work visa quickly through an agent for a small fee?',
    answer: 'MYTH: Legitimate visa processes take time and have specific fees set by embassies. Anyone promising quick visas for unusually low fees is likely running a scam. Always work with official channels.',
    category: 'safety',
    votes: 189,
    isMyth: true,
  },
  {
    id: '3',
    country: 'senegal',
    question: 'Combien coûte généralement le processus de migration légale?',
    answer: 'Les coûts varient considérablement selon le pays de destination, le type de visa et vos circonstances individuelles. Comptez entre 500 et 3000 euros pour les frais officiels, sans compter les billets d\'avion et les autres dépenses.',
    category: 'legal',
    votes: 156,
    isMyth: false,
  },
  {
    id: '4',
    country: 'morocco',
    question: 'هل يمكنني العمل في أي دولة أوروبية بدون تأشيرة؟',
    answer: 'خرافة: جميع الدول الأوروبية تتطلب تأشيرة عمل مناسبة للمواطنين من خارج الاتحاد الأوروبي. العمل بدون التصاريح المناسبة غير قانوني وقد يؤدي إلى الترحيل.',
    category: 'employment',
    votes: 203,
    isMyth: true,
  },
  {
    id: '5',
    country: 'kenya',
    question: 'Je, ninahitaji bima ya afya kusafiri nje ya nchi?',
    answer: 'Ndiyo, bima ya afya ya usafiri ni muhimu sana na inaweza kuwa mahitaji ya lazima kwa baadhi ya nchi. Inakulinda dhidi ya gharama kubwa za matibabu ikiwa utaumwa unapokuwa mbali na nyumbani.',
    category: 'health',
    votes: 178,
    isMyth: false,
  },
];

// Campaign Library Mock Data
export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    country: ['nigeria', 'kenya'],
    title: 'Know Before You Go: Safe Migration Guide',
    slug: 'know-before-you-go',
    description: 'A comprehensive video series covering the essential steps for safe and legal migration.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=600&fit=crop',
    mediaUrl: 'https://example.com/videos/safe-migration-guide.mp4',
    duration: 1245,
    fileSize: 45000000,
    tags: ['safety', 'legal', 'guide'],
    category: 'awareness',
    publishedDate: '2025-09-20',
    views: 12450,
    downloads: 3421,
    shares: 892,
  },
  {
    id: '2',
    country: ['senegal'],
    title: 'Évitez les Arnaques de Migration',
    slug: 'evitez-arnaques-migration',
    description: 'Guide audio sur comment identifier et éviter les escroqueries liées à la migration.',
    mediaType: 'audio',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&h=600&fit=crop',
    mediaUrl: 'https://example.com/audio/evitez-arnaques.mp3',
    duration: 780,
    fileSize: 12000000,
    tags: ['sécurité', 'fraude', 'prévention'],
    category: 'prevention',
    publishedDate: '2025-09-15',
    views: 8930,
    downloads: 2156,
    shares: 543,
  },
  {
    id: '3',
    country: ['morocco'],
    title: 'حقوقك في العمل بالخارج',
    slug: 'your-rights-work-abroad',
    description: 'رسم معلوماتي يوضح حقوق العمال المهاجرين وكيفية حمايتها.',
    mediaType: 'infographic',
    thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    mediaUrl: 'https://example.com/infographics/worker-rights-ar.pdf',
    tags: ['حقوق', 'عمل', 'حماية'],
    category: 'protection',
    publishedDate: '2025-09-25',
    views: 15670,
    downloads: 5432,
    shares: 1234,
  },
  {
    id: '4',
    country: ['kenya', 'nigeria'],
    title: 'Community Support Networks for Migrants',
    slug: 'community-support-networks',
    description: 'Documentary showcasing successful community-based support systems for migrants.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop',
    mediaUrl: 'https://example.com/videos/community-support.mp4',
    duration: 2100,
    fileSize: 78000000,
    tags: ['community', 'support', 'networks'],
    category: 'community',
    publishedDate: '2025-10-01',
    views: 9876,
    downloads: 1987,
    shares: 654,
  },
  {
    id: '5',
    country: ['senegal', 'morocco'],
    title: 'Guide des Ressources Locales',
    slug: 'guide-ressources-locales',
    description: 'Document PDF contenant des contacts et ressources utiles pour les migrants.',
    mediaType: 'document',
    thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop',
    mediaUrl: 'https://example.com/documents/ressources-locales.pdf',
    tags: ['ressources', 'contacts', 'aide'],
    category: 'resources',
    publishedDate: '2025-10-05',
    views: 7654,
    downloads: 4321,
    shares: 432,
  },
];

// Training Modules Mock Data
export const mockTrainingModules: TrainingModule[] = [
  {
    id: '1',
    title: 'Safe Migration Fundamentals',
    description: 'Learn the essential knowledge for planning a safe and legal migration journey.',
    country: ['nigeria', 'kenya'],
    lessons: [],
    totalDuration: 3600,
    difficulty: 'beginner',
    enrollmentCount: 4532,
  },
  {
    id: '2',
    title: 'Prévention de la Traite des Personnes',
    description: 'Comprendre les tactiques de traite et comment se protéger.',
    country: ['senegal'],
    lessons: [],
    totalDuration: 2700,
    difficulty: 'intermediate',
    enrollmentCount: 2876,
  },
  {
    id: '3',
    title: 'حقوق العمال المهاجرين',
    description: 'تعرف على حقوقك القانونية كعامل مهاجر وكيفية الدفاع عنها.',
    country: ['morocco'],
    lessons: [],
    totalDuration: 3200,
    difficulty: 'intermediate',
    enrollmentCount: 3421,
  },
];

export const mockLessons: Lesson[] = [
  {
    id: '1',
    moduleId: '1',
    title: 'Understanding Migration Pathways',
    slug: 'understanding-migration-pathways',
    description: 'Explore the different legal pathways for migration and which might be right for you.',
    duration: 900,
    order: 1,
    content: [
      {
        type: 'text',
        content: 'There are several legal pathways for migration, each with specific requirements and processes...',
      },
      {
        type: 'video',
        content: 'https://example.com/lessons/pathways-intro.mp4',
        duration: 420,
      },
    ],
    prerequisites: [],
    completionRate: 78,
  },
  {
    id: '2',
    moduleId: '1',
    title: 'Required Documentation',
    slug: 'required-documentation',
    description: 'Learn about the essential documents needed for legal migration.',
    duration: 720,
    order: 2,
    content: [
      {
        type: 'text',
        content: 'Proper documentation is crucial for legal migration. Here\'s what you typically need...',
      },
    ],
    prerequisites: ['1'],
    completionRate: 65,
  },
];

export const mockQuiz: Quiz = {
  id: '1',
  lessonId: '1',
  questions: [
    {
      id: 'q1',
      question: 'Which document is required for international travel?',
      type: 'multiple-choice',
      options: ['Driver\'s License', 'Valid Passport', 'Birth Certificate', 'School ID'],
      correctAnswer: 1,
      explanation: 'A valid passport is essential for international travel and is required by all countries.',
      points: 10,
    },
    {
      id: 'q2',
      question: 'You should only work with official embassy channels for visa applications.',
      type: 'true-false',
      options: ['True', 'False'],
      correctAnswer: 0,
      explanation: 'Always work through official channels to avoid scams and ensure legitimate processing.',
      points: 10,
    },
    {
      id: 'q3',
      question: 'Which of the following are red flags for migration scams? (Select all that apply)',
      type: 'multi-select',
      options: [
        'Promises of guaranteed visas',
        'Requests for upfront payment',
        'Pressure to decide quickly',
        'Official embassy documentation',
      ],
      correctAnswer: [0, 1, 2],
      explanation: 'Scammers often use pressure tactics and guarantees. Official processes never guarantee outcomes.',
      points: 15,
    },
  ],
  passingScore: 70,
  timeLimit: 15,
};

// Analytics Mock Data
export const mockAnalyticsMetrics: AnalyticsMetric[] = [
  {
    id: '1',
    metric: 'Total Users',
    value: 45678,
    change: 12.5,
    period: 'month',
  },
  {
    id: '2',
    metric: 'Page Views',
    value: 234567,
    change: 8.3,
    period: 'month',
  },
  {
    id: '3',
    metric: 'Training Enrollments',
    value: 3421,
    change: 23.7,
    period: 'month',
  },
  {
    id: '4',
    metric: 'Campaign Downloads',
    value: 12345,
    change: 15.2,
    period: 'month',
  },
];

export const mockEngagementData: EngagementData[] = [
  { date: '2025-10-01', pageViews: 12500, uniqueVisitors: 3400, avgSessionDuration: 245, bounceRate: 42 },
  { date: '2025-10-02', pageViews: 13200, uniqueVisitors: 3600, avgSessionDuration: 258, bounceRate: 40 },
  { date: '2025-10-03', pageViews: 11800, uniqueVisitors: 3200, avgSessionDuration: 232, bounceRate: 45 },
  { date: '2025-10-04', pageViews: 14100, uniqueVisitors: 3850, avgSessionDuration: 267, bounceRate: 38 },
  { date: '2025-10-05', pageViews: 13500, uniqueVisitors: 3700, avgSessionDuration: 254, bounceRate: 41 },
  { date: '2025-10-06', pageViews: 12900, uniqueVisitors: 3500, avgSessionDuration: 248, bounceRate: 43 },
  { date: '2025-10-07', pageViews: 15600, uniqueVisitors: 4200, avgSessionDuration: 278, bounceRate: 36 },
];

export const mockGeoData: GeoData[] = [
  { country: 'nigeria', sessions: 18500, users: 5200, avgDuration: 265 },
  { country: 'kenya', sessions: 12300, users: 3800, avgDuration: 248 },
  { country: 'senegal', sessions: 9800, users: 2900, avgDuration: 234 },
  { country: 'morocco', sessions: 11200, users: 3400, avgDuration: 256 },
];

export const mockDeviceData: DeviceData[] = [
  { deviceType: 'mobile', percentage: 68, sessions: 35420 },
  { deviceType: 'desktop', percentage: 24, sessions: 12500 },
  { deviceType: 'tablet', percentage: 8, sessions: 4170 },
];
